### PR TITLE
added PP_EACH_LIST that adds commas's between elements

### PR DESCRIPTION
**Pull request by OndrejPopp**
Hi Cormac,
This pull request adds PP_EACH_LIST that adds comma's between the elements. I don't know if I  am using it the right  way, and I have not tested the simple cases but with the following macros,

```
#define __traceArg(x) {#x, Tracer::toString(x)}
#define __traceConcat(a, b) __traceConcatInner(a, b)
#define __traceConcatInner(a, b) a##b

#define __traceExplicitFormat(f, ...) Tracer __traceConcat(__tracer, __LINE__) \
                                      {f, __FILE__, __LINE__, __PRETTY_FUNCTION__, {__VA_ARGS__}}

#define __traceFormat(f, ...) __traceExplicitFormat(f, PP_EACH_LIST(__traceArg, __VA_ARGS__))
#define __trace(...) __traceFormat(Tracer::Format::InOut, __VA_ARGS__)
```
I don't  get the comma's in my initializer list with PP_EACH.  Shortly, __trace(a, b) does not expand into Tracer t(... {{"a", a}, {"b", b}}) but concerning the initializer  list only to {{"a", a}   {"b", b}} with a missing comma between the elements.

PP_EACH_LIST fixes this. I  tried further to make a generic PP_EACH with an extra separator parameter but I  could not get that working properly because this macro expansion stuff is tricky... So in the end I  just moved in a new section, PP_EACH_LIST.

Thanks, and I  hope you are doing alright concerning Brexit?
Ondrej

### CODE REVIEW

**Comment by cormacc** [comment]
Thanks for the contribution Ondrej. In the final throes of a release at work, but should get time to review properly towards the end of the week - find this recursive variadic macro stuff very useful, but slightly head-melting - takes me a clear half day to get my head back into it after a break :) Finding Brexit hilarious/depressing/baffling, but only peripherally affected so far, thanks - I'm based in the Republic of Ireland rather than Northern Ireland

**Comment by cormacc** [comment]
OK - now I get it - interesting corner case. In pp_enum.h there's similar list construction, but the implementation leaves a final trailing comma which is acceptable in an enum definition or array initialiser, but not at the end of a list of arguments to a function call (see below for the approach used in pp_enum.h)
``` c
#define _ENUM_TAG_(NAME) #NAME,
#define _ENUM_TAGS_AUTO_(IDS) PP_EACH(_ENUM_TAG_, IDS)
#define ENUM_TAGS_AUTO(NAME)                         \
  static char const * NAME##_TAGS[] = {         \
    _ENUM_TAGS_AUTO_(NAME##Tags)                      \
  }
```
Happy to merge this, but a couple of bits of housekeeping first:
1. Naming - can we call it PP_LIST_EACH rather than PP_EACH_LIST -- means we can add PP_LIST_EACH_IDX PP_LIST_PAR_EACH_IDX later if necessary, with consistent namespacing.
2. Can you propagate the change to the ruby generator pp_iterators.rb? I've just pushed a commit to master that includes a placeholder entry for it you can populate.

**Comment by OndrejPopp** [comment]
Hi Cormac,
Ok - now I get it - I did not notice that the pp_iter.h file was auto generated. So ok, I can propagate it but the only thing is that I never programmed in Ruby before but I just looked it over and based on what is there and the place holders you put in I can manage that :)

So, I am going to pull this in, then make the generator work and then commit to the same branch that I already created and then you will get it in the same pull request. 

Ok?

We have now nice weather here in the Netherlands how is the weather in Southern Ireland?

Ondrej

**Comment by cormacc** [comment]
Yeah exactly -- rebase your branch on latest master, then make the updates and 'git push --force' to your own branch (the force is necessary as rebasing rewrites history). The merge request should pick up the changes automagically

I can make the generator updates no problem if you run into issues -- just didn't want to hijack your pull request and replace it with my own commit, kind of thing.

The reason I used a generator initially is that this began as an effort to extend the excellent fake function framework, but the scope of application broadened subsequently. Before introducing tail recursion, the generator was very helpful to avoid a lot of tedious manual/error-prone repetition related sets of macros (one for each number of arguments). Post tail-recursion, it's still useful for the arg counting macros and allowing customisation of the max supported arg count, but somewhat less relevant.

fake function framework : https://github.com/meekrosoft/fff

**Comment by OndrejPopp** [comment]
Ok I see.
I would not have minded if you would have modified my commit but now you have prepared it for me the way you did I accept your invitation!




⁣Get BlueMail for Android ​

**Comment by OndrejPopp** [comment]
Ok, done.

**Comment by cormacc** [comment]
Thank you kindly Ondrej - merged.
Actually I'll add a note to the readme in another commit

**Comment by cormacc** [comment]
@OndrejPopp - Updated the readme to reference the addition. Also renamed PP_LIST_EACH to PP_COMMA_EACH (I clearly have difficultly making up my mind :) ) - seemed clearer, semantically. Thanks again for the contribution.

**Comment by OndrejPopp** [comment]
You're welcome Cormac 🙂

⁣Get BlueMail for Android ​

**Comment by OndrejPopp** [comment]
Ok, just saw it when I fetched from you. I already updated my own trace macros to PP_COMMA_EACH, and switched to your master. I called it LIST because lists have comma's.. (and function arguments too, which you can also call an argument list) But COMMA is fine for me as well. So I am not suggesting anything!

Someone said once that figuring out the right names is one of the difficult tasks in software development. So I have that as well renaming things a few times before it settles...

My thanks back to you for this library and the merge.

Ondrej


⁣Get BlueMail for Android ​

On Jun 24, 2022, 11:21, at 11:21, Cormac Cannon ***@***.***> wrote:
***@***.*** - Updated the readme to reference the addition. Also

**Pull request merged**
